const path = require('path');

module.exports = {
  extends: [
    'tslint:recommended',
    'tslint-consistent-codestyle',
    'tslint-microsoft-contrib',
    'tslint-eslint-rules',
  ],
  rules: {
    'prefer-const': true,
    'no-var-keyword': true,
    'no-var-requires': false,
    'interface-name': [true, 'never-prefix'],
    'object-literal-shorthand': true,
    'object-shorthand-properties-first': true,
    'object-literal-key-quotes': [true, 'as-needed'],
    'prefer-array-literal': true,
    quotemark: [true, 'single', 'jsx-double'],
    'prefer-template': true,
    'no-eval': true,
    'no-function-constructor-with-string-args': true,
    'space-before-function-paren': [
      true,
      {
        anonymous: 'always',
        named: 'never',
      },
    ],
    'no-parameter-reassignment': true,
    align: [true, 'arguments', 'parameters'],
    'ter-prefer-arrow-callback': [true],
    'arrow-parens': false,
    'ter-arrow-parens': [true, 'as-needed', { requireForBlockBody: true }],
    'no-duplicate-imports': true,
    'one-variable-per-declaration': [true, 'ignore-for-loop'],
    'no-increment-decrement': true,
    'triple-equals': [true, 'allow-null-check'],
    curly: [true, 'ignore-same-line'],
    'brace-style': [true, '1tbs', { allowSingleLine: true }],
    'no-else-after-return': true,
    'comment-format': [true, 'check-space'],
    indent: [true, 'space'],
    'ter-indent': [true, 2, { SwitchCase: 1 }],
    whitespace: [
      true,
      'check-branch',
      'check-decl',
      'check-operator',
      'check-module',
      'check-separator',
      'check-rest-spread',
      'check-type',
      'check-typecast',
      'check-type-operator',
      'check-preblock',
    ],
    'object-literal-sort-keys': false,
    eofline: true,
    'space-in-parens': [true, 'never'],
    'array-bracket-spacing': [true, 'never'],
    'object-curly-spacing': [true, 'always'],
    'max-line-length': [true, 100],
    'block-spacing': true,
    'ter-computed-property-spacing': true,
    'ter-func-call-spacing': true,
    'no-trailing-whitespace': true,
    'no-consecutive-blank-lines': true,
    'trailing-comma': [
      true,
      {
        multiline: 'never',
        singleline: 'never',
        esSpecCompliant: true,
      },
    ],
    semicolon: [true, 'never'],
    'no-construct': true,
    radix: true,
    'function-name': [
      true,
      {
        'function-regex': /^[a-z$][\w\d]+$/,
        'method-regex': /^[a-z$][\w\d]+$/,
        'private-method-regex': /^[a-z$][\w\d]+$/,
        'protected-method-regex': /^[a-z$][\w\d]+$/,
        'static-method-regex': /^[a-z$][\w\d]+$/,
      },
    ],
    'variable-name': [true, 'check-format'],
    'class-name': true,
    'no-this-assignment': [true, 'allow-destructuring'],
    'import-name': true,
  },
};
